### ISSUE TITLE
Error window "Could not find file"

### ISSUE THREAD

**Issue by phfu** [Christian-ALLEGRE/WsjtxAdiMerger#2] opened 2024-02-17 16:02 UTC
![2024-02-17 16_59_46-WsjtxAdiMerger par F4LAA V1 1a (17_02_2024 16_00)](https://github.com/Christian-ALLEGRE/WsjtxAdiMerger/assets/31780464/a57ad545-9082-48a9-9e6c-288171b588c7)
![image](https://github.com/Christian-ALLEGRE/WsjtxAdiMerger/assets/31780464/4ea9e52e-4ac3-4d48-86df-0c4f7118be49)

**Comment by Christian-ALLEGRE** [comment] 2024-02-17 22:42
This was caused by a selected file name who did not contains the expected "_log" string, who should be replaced by "_144MHz" to create the wsjtx_144MHz.adi file.
Fixed in V1.1b : Now, you can't select a file where it's name do not contain the "wsjtx_log.adi" string.

**Closed as completed by Christian-ALLEGRE** 2024-02-17 22:42 UTC
